version: '3.3'
volumes:
  postgres-data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - /var/log/postgresql/:/var/log/postgresql/
    env_file:
      - .env
  web:
    image: chuzhinoves/math_quiz:latest
    volumes:
        - .static:/code/static/
        - .media:/code/media/
    restart: always
    depends_on:
      - db
    env_file:
      - .env 
  nginx:
    image: nginx
    volumes:
        - .static:/code/static/
        - .media:/code/media/
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - /var/log/nginx/:/var/log/nginx/
    restart: always
    ports:
        - "8080:80"
    depends_on:
        - web